import 'package:package_test/_importer.dart';

class Curriculum {
  String? _title;
  List<BigUnit>? _bigUnit;

  Autogenerated({String? title, List<BigUnit>? bigUnit}) {
    if (title != null) {
      _title = title;
    }
    if (bigUnit != null) {
      _bigUnit = bigUnit;
    }
  }

  String? get title => _title;
  set title(String? title) => _title = title;
  List<BigUnit>? get bigUnit => _bigUnit;
  set bigUnit(List<BigUnit>? bigUnit) => _bigUnit = bigUnit;

  Curriculum.fromJson(Map<String, dynamic> json) {
    _title = json['title'];
    if (json['bigUnit'] != null) {
      _bigUnit = <BigUnit>[];
      json['bigUnit'].forEach((v) {
        _bigUnit!.add(BigUnit.fromJson(v));
      });
    }
  }
}